layout_spectrum: 0.3442535
color:
  saturation: 0.2713237
  lightness: 0.323058
  brandStrength: 0.5407023
  rhythmicContrast: 0.3129786
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.555711
name: TheAspire
